---
# tasks file for rhds10

- name: register and subscribe to a specific pool by ID.
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    pool_ids: "{{ rhn_pool_id }}"

# - name: Disable all RHSM repositories
#   rhsm_repository:
#     name: '*'
#     state: disabled

- name: Enable rhel 7 repository for DS
  rhsm_repository:
    name: rhel-7-server-rhds-10-rpms
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int = 7

- name: Enable 8 repository for DS
  rhsm_repository:
    name: rhel-x8xxx-server-rhds-10-rpms
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int = 8

- name: install DS package
  package:
    name: redhat-ds